---
- hosts: all
  become: yes
  tasks:
    - name: creating file
      file:
        path: /home/ec2-user/uncle
        state: touch
    - name: creating folder
      file:
        path: /home/ec2-user/aunty
        state: directory
    - name: intall java
      get_url:
        url: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u352b08.tar.gz
        dest: /home/ec2-user/
    - name: untar
      unarchive:
        src: /home/ec2-user/OpenJDK8U-jdk_x64_linux_hotspot_8u352b08.tar.gz
        dest: /home/ec2-user/
        remote_src: yes
    - name: remane java
      copy:
        remote_src: true
        src: /home/ec2-user/jdk8u352-b08
        dest: /home/ec2-user/java8
    - name: remove
      file:
        path: /home/ec2-user/OpenJDK8U-jdk_x64_linux_hotspot_8u352b08.tar.gz
        state: absent
    - name: remove
      file:
        path: /home/ec2-user/jdk8u352-b08
        state: absent
    - name:
      lineinfile:
        dest: /etc/profile
        line: "export JAVA_HOME=/opt/java8 \n export PATH=$PATH:/opt/java8/bin"
        state: present
        create: True
    - name: install tomcat9
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz
        dest: /opt/
    - name: untar tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.69.tar.gz
        dest: /opt
        remote_src: yes
    - name: rename
      copy:
        remote_src: true
        src: /opt/apache-tomcat-9.0.69
        dest: /opt/tomcat9
    - name: remove
      file:
        path: /opt/apache-tomcat-9.0.69.tar.gz
        state: absent
    - name: remove
      file:
        path: /opt/apache-tomcat-9.0.69
        state: absent
    - shell: "sudo chown -R ec2-user:ec2-user /opt/tomcat9"
    - command: "cd /opt/tomcat9/bin"
    - name: start tomcat9
      command: "nohup /opt/tomcat9/bin/startup.sh"
    - name: warfile
      get_url:
        url: https://saichand123.s3.amazonaws.com/petclinic.war
        dest: /opt/tomcat9/webapps/

